# .goreleaser.yml
release:
  github:
    owner: foresturquhart
    name: grimoire

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: linux
        goarch: ppc64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: s390x
    dir: .
    main: ./cmd/grimoire
    binary: grimoire
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'