version: 2

release:
  github:
    owner: foresturquhart
    name: grimoire

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/grimoire
    binary: grimoire

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'