name: Release Grimoire
on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: 1.23.4

jobs:
  release:
    name: Release
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release -f .goreleaser.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}